(djangoproject) C:\Users\molin>Desktop/UOC/Anaconda_exercices/Readthedocs
"Desktop" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(djangoproject) C:\Users\molin>cd Desktop/UOC/Anaconda_exercices/Readthedocs

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>django-admin startproject mysite

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>python manage.py migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>cd Desktop/UOC/Anaconda_exercices/Readthedocs/mysite
El sistema no puede encontrar la ruta especificada.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>cd Readthedocs/mysite
El sistema no puede encontrar la ruta especificada.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>python manage.py migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>ls
"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>python manage.py migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>cd Desktop/UOC/Anaconda_exercices/Readthedocs/mysite
El sistema no puede encontrar la ruta especificada.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>cd Desktop/UOC/Anaconda_exercices/Readthedocs/mysite
El sistema no puede encontrar la ruta especificada.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs>cd mysite

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
March 09, 2019 - 17:40:52
Django version 2.1.7, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[09/Mar/2019 17:41:25] "GET / HTTP/1.1" 200 16348
[09/Mar/2019 17:41:25] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[09/Mar/2019 17:41:25] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[09/Mar/2019 17:41:25] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[09/Mar/2019 17:41:25] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
Not Found: /favicon.ico
[09/Mar/2019 17:41:25] "GET /favicon.ico HTTP/1.1" 404 1972
[09/Mar/2019 17:45:08] "GET / HTTP/1.1" 200 16348
[09/Mar/2019 17:45:14] "GET / HTTP/1.1" 200 16348
[09/Mar/2019 17:45:20] "GET / HTTP/1.1" 200 16348
[09/Mar/2019 17:50:22] "GET / HTTP/1.1" 200 16348

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
March 09, 2019 - 17:51:07
Django version 2.1.7, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py startapp polls

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py makemigrations polls
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py makemigrations polls
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py sqlmigrate polls 0001
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001463EB7E268>
Traceback (most recent call last):
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py startapp polls
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001E08FC3E268>
Traceback (most recent call last):
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>cd Polls

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls>python manage.py makemigrations polls
python: can't open file 'manage.py': [Errno 2] No such file or directory

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\pollscd Desktop/UOC/Anaconda_exercices/Readthedocs/mysite
El sistema no puede encontrar la ruta especificada.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\pollscd Desktop/UOC/Anaconda_exercices/Readthedocs/mysite
El sistema no puede encontrar la ruta especificada.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls>ls
"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\pollscd C:/Users/molin/Desktop/UOC/Anaconda_exercices/Readthedocs/mysite

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py makemigrations polls
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py sqlmigrate polls 0001
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

(djangoproject) C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite>python manage.py check
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\molin\Anaconda3\envs\djangoproject\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 9, in <module>
    class Choice(models.Model):
  File "C:\Users\molin\Desktop\UOC\Anaconda_exercices\Readthedocs\mysite\polls\models.py", line 10, in Choice
    question = models.ForeignKey(Question)
TypeError: __init__() missing 1 required positional argument: 'on_delete'